export const AdminLinks = {
  base: "/admin",
  login: "/admin/login",
  product: "/admin/product",
  addProduct: "/admin/product/add",
  updateProduct: "/admin/product/update",
  updateSpecifications: "/admin/product/updateSpec",
  createSpecifications: "/admin/product/specificationsAdd",
  editSpecifications: "/admin/product/editSpec",
  order: "/admin/order",
  orderItems: "/admin/orderItems",
  user: "/admin/user",
  categoryAndBrand: "/admin/categoryAndBrand",
  fagAdd: "/admin/fag/add",
  fag: "/admin/fag",
};
